### ISSUE TITLE
Program name is interpreted as positional argument without `.add_command()`

### ISSUE THREAD

**Issue by kdallasd** [sagiegurari/cliparser#2]
### Describe The Bug
If your spec does not include an `add_command` statement, the program name is interpreted as a positional argument when using `parse_process`. This will cause an unexpected failure.

The documentation implies that `add_command` is optional, with the statement `// If not defined, the parsing will start checking the arguments only.`

Note: confirmed behavior in Linux and Windows

### Code Sample
Very minimal example based on your documentation, just without specifying `add_command` or `add_subcommand`. If run, the program exits, saying "Positional arguments found but not allowed per spec"

```rust
use cliparser::types::{
    Argument, ArgumentHelp, ArgumentOccurrence, ArgumentValueType, CliSpec, CliSpecMetaInfo,
    PositionalArgument,
};
use cliparser::{help, parse_process, version};
use std::collections::{HashMap, HashSet};

fn main() {
    let mut cli_spec = CliSpec::new();

    cli_spec = cli_spec
        .add_argument(Argument {
            name: "flag".to_string(),
            key: vec!["--flag".to_string(), "-f".to_string()],
            argument_occurrence: ArgumentOccurrence::Single,
            value_type: ArgumentValueType::None,
            default_value: None,
            help: Some(ArgumentHelp::Text(
                "A flag without value example".to_string(),
            )),
        });

    let result = parse_process(&cli_spec);

    if result.is_err() {
        println!("{}", result.err().unwrap());
        std::process::exit(1);
    }

    let cli_parsed = result.unwrap();
    println!("Cli Parsed:\n{:?}", &cli_parsed);
}

```

**Comment by sagiegurari** [comment]
thats expected. so if you didn't specify the command name than the parser assumes everything you provided are the args after the command line.
this allows you to provide and parse only args.
i feel I'm not explanating it well

**Comment by kdallasd** [comment]
That makes sense. I feel the example documentation could be a little clearer on this issue. 

While I believe it _would_ be nice to not have to specify the program name, it is not a difficult thing to do.

**Comment by sagiegurari** [comment]
1. if you have an example you want to add to the readme, feel free to PR it
2. didn't fully get the second part...
